version: '3'

services:
  app:
    build: .
    container_name: guitar-store-app
    volumes:
      - ./:/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - DB_HOST=${DB_HOST}
      - APP_PORT=${APP_PORT}
      # - DB_USER=${DB_USER}
      # - DB_PASS=${DB_PASS}
      # - REDIS_URL=${REDIS_URL}
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-network
  db:
    image: mongo
    container_name: guitar-store-mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
    ports:
      - 0.0.0.0:27017:27017
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  mongodbdata:
